receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:

  otlp_grpc/grafana:
    endpoint: grafana:4317
    tls:
      insecure: true

  otlp_grpc/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    format: proto

  otlp_http/seq:
    endpoint: http://seq/ingest/otlp

  otlp_grpc/aspire:
    endpoint: aspire:18889
    tls:
      insecure: true

  otlp_grpc/honeycomb:
    endpoint: api.honeycomb.io:443
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
